import logging
from pathlib import Path

logger = logging.getLogger(__name__)

async def synthesize_speech(text: str, output_path: Path, engine: str = "edge-tts", voice: str = "en-US-AriaNeural"):
    """
    Synthesize text to speech using the selected engine.
    """
    logger.info(f"Synthesizing with {engine}, voice {voice}")
    
    if engine == "edge-tts":
        import edge_tts
        communicate = edge_tts.Communicate(text, voice)
        await communicate.save(str(output_path))
        
    elif engine == "kokoro":
        # Note: requires the kokoro package and local model weights
        from kokoro import KPipeline
        import soundfile as sf
        
        # Initialize pipeline (this should ideally be cached globally in a production app)
        pipeline = KPipeline(lang_code='a') 
        generator = pipeline(text, voice=voice, speed=1.0, split_pattern=r'\n+')
        
        audio_segments = []
        sample_rate = 24000
        for i, (gs, ps, audio) in enumerate(generator):
            audio_segments.append(audio)
            
        if audio_segments:
            import numpy as np
            final_audio = np.concatenate(audio_segments)
            sf.write(str(output_path), final_audio, sample_rate)
        else:
            raise ValueError("No audio generated by Kokoro.")
            
    else:
        raise NotImplementedError(f"TTS engine {engine} not implemented.")
